#ifndef __fdmdv2TopFrame__
#define __fdmdv2TopFrame__

/**
@file
Subclass of TopFrame, which is generated by wxFormBuilder.
*/

#include "topFrame.h"

//// end generated include

/** Implementing TopFrame */
class fdmdv2TopFrame : public TopFrame
{
	protected:
		// Handlers for TopFrame events.
		void topFrame_OnClose( wxCloseEvent& event );
		void topFrame_OnPaint( wxPaintEvent& event );
		void topFrame_OnSize( wxSizeEvent& event );
		void topFrame_OnUpdateUI( wxUpdateUIEvent& event );
		void OnOpen( wxCommandEvent& event );
		void OnOpenUpdateUI( wxUpdateUIEvent& event );
		void OnSave( wxCommandEvent& event );
		void OnSaveUpdateUI( wxUpdateUIEvent& event );
		void OnClose( wxCommandEvent& event );
		void OnCloseUpdateUI( wxUpdateUIEvent& event );
		void OnExit( wxCommandEvent& event );
		void OnCopy( wxCommandEvent& event );
		void OnCopyUpdateUI( wxUpdateUIEvent& event );
		void OnCut( wxCommandEvent& event );
		void OnCutUpdateUI( wxUpdateUIEvent& event );
		void OnPaste( wxCommandEvent& event );
		void OnPasteUpdateUI( wxUpdateUIEvent& event );
		void OnToolsAudio( wxCommandEvent& event );
		void OnToolsAudioUI( wxUpdateUIEvent& event );
		void OnToolsComCfg( wxCommandEvent& event );
		void OnToolsComCfgUI( wxUpdateUIEvent& event );
		void OnToolsOptions( wxCommandEvent& event );
		void OnToolsOptionsUI( wxUpdateUIEvent& event );
		void OnHelpCheckUpdates( wxCommandEvent& event );
		void OnHelpCheckUpdatesUI( wxUpdateUIEvent& event );
		void OnHelpAbout( wxCommandEvent& event );
		void OnTogBtnRxID( wxCommandEvent& event );
		void OnTogBtnTxID( wxCommandEvent& event );
		void OnCmdSliderScroll( wxScrollEvent& event );
		void OnSliderScrollBottom( wxScrollEvent& event );
		void OnCmdSliderScrollChanged( wxScrollEvent& event );
		void OnSliderScrollTop( wxScrollEvent& event );
		void OnCheckSQClick( wxCommandEvent& event );
		void OnTogBtnSplitClick( wxCommandEvent& event );
		void OnTogBtnAnalogClick( wxCommandEvent& event );
		void OnTogBtnALCClick( wxCommandEvent& event );
		void OnTogBtnTXClick( wxCommandEvent& event );
	public:
		/** Constructor */
		fdmdv2TopFrame( wxWindow* parent );
	//// end generated class members
	
};

#endif // __fdmdv2TopFrame__
