#ifndef __fdmdv2DlgAudio__
#define __fdmdv2DlgAudio__

/**
@file
Subclass of DlgAudio, which is generated by wxFormBuilder.
*/

#include "topFrame.h"

//// end generated include

/** Implementing DlgAudio */
class fdmdv2DlgAudio : public DlgAudio
{
	protected:
		// Handlers for DlgAudio events.
		void OnApply( wxCommandEvent& event );
		void OnCancel( wxCommandEvent& event );
		void OnOK( wxCommandEvent& event );
	public:
		/** Constructor */
		fdmdv2DlgAudio( wxWindow* parent );
	//// end generated class members
	
};

#endif // __fdmdv2DlgAudio__
