#ifndef FREEDV_VER_DOT_H
#define FREEDV_VER_DOT_H 1

#define FREEDV_VERSION_MAJOR 0
#define FREEDV_VERSION_MINOR 96
#define FREEDV_VERSION_PATCH 5
#define FREEDV_VERSION_SUFFIX "Beta"

#define FREEDV_VERSION "0.96.5 Beta"

#endif //FREEDV_VER_DOT_H
